

ServerEvents.recipes(event => {
    let remove_id = [
        'enderio:primitive_alloy_smelter',
        'allthemodium:teleport_pad',
        'alltheores:aluminum_gear',
        'alltheores:iridium_gear',
        'alltheores:osmium_gear',
        'alltheores:platinum_gear',
        'alltheores:uranium_gear',
        'alltheores:zinc_gear',
        'alltheores:brass_gear',
        'thermal_extra:parts/soul_infused_gear',
        'thermal_extra:parts/shellite_gear',
        'thermal_extra:parts/twinite_gear',
        'thermal_extra:parts/dragonsteel_gear',
        'alltheores:steel_gear',
        'thermal:parts/rose_gold_gear',
        'alltheores:tin_gear',
        'alltheores:lead_gear',
        'alltheores:silver_gear',
        'redstone_arsenal:materials/flux_gear',
        'alltheores:enderium_gear',
        'alltheores:lumium_gear',
        'alltheores:signalum_gear',
        'thermal:parts/quartz_gear',
        'thermal:parts/emerald_gear',
        'alltheores:diamond_gear',
        'thermal:parts/lapis_gear',
        'thermal:parts/netherite_gear',
        'alltheores:copper_gear',
        'alltheores:nickel_gear',
        'alltheores:bronze_gear',
        'alltheores:electrum_gear',
        'alltheores:invar_gear',
        'alltheores:constantan_gear',
        'alltheores:iron_gear',
        'alltheores:gold_gear',
        'jaopca:storage_blocks.to_storage_block.grains_of_infinity',
        'jaopca:thermal_expansion.material_to_storage_block.grains_of_infinity',
        'enderio:iron_gear',
        'systeams:boiler_pipe',
        'thermal:fire_charge/enderium_ingot_2',
        'thermal:fire_charge/lumium_ingot_4',
        'thermal:fire_charge/signalum_ingot_4',
        'thermal:enderium_dust_2',
        'thermal:lumium_dust_4',
        'thermal:machines/smelter/smelter_alloy_enderium',
        'alltheores:enderium_ingot_from_dust',
        'thermal:machines/smelter/smelter_enderium_dust',
        'alltheores:enderium_ingot_from_dust_blasting',
        'thermal:machines/smelter/smelter_alloy_rose_gold',
        'thermal:smelting/rose_gold_ingot_from_dust_smelting',
        'thermal:smelting/rose_gold_ingot_from_dust_blasting',
        'thermal_extra:smelting/dragonsteel_ingot_from_dust_smelting',
        'thermal_extra:smelting/dragonsteel_ingot_from_dust_blasting',
        'thermal_extra:machine/smelter/dragonsteel_ingot',
        'jaopca:thermal_expansion.dust_to_material.dragonsteel',
        'thermal_extra:machine/smelter/dragonsteel_ingot_from_dust',
        'thermal_extra:machine/smelter/soul_infused_ingot',
        'jaopca:thermal_expansion.dust_to_material.soul_infused',
        'thermal_extra:machine/smelter/soul_infused_ingot_from_dust',
        'thermal_extra:smelting/soul_infused_ingot_from_dust_smelting',
        'thermal_extra:smelting/soul_infused_ingot_from_dust_blasting',
        'thermal_extra:smelting/shellite_ingot_from_dust_smelting',
        'thermal_extra:smelting/shellite_ingot_from_dust_blasting',
        'jaopca:thermal_expansion.dust_to_material.shellite',
        'thermal_extra:machine/smelter/shellite_ingot',
        'thermal_extra:machine/smelter/shellite_ingot_from_dust',
        'thermal_extra:smelting/twinite_ingot_from_dust_smelting',
        'thermal_extra:smelting/twinite_ingot_from_dust_blasting',
        'jaopca:thermal_expansion.dust_to_material.twinite',
        'thermal_extra:machine/smelter/twinite_ingot_from_dust',
        'thermal_extra:machine/smelter/twinite_ingot',
        'mekanism:steel_casing',
        'mekanism:factory/elite/smelting',
        'mekanism:factory/elite/enriching',
        'mekanism:factory/elite/crushing',
        'mekanism:factory/elite/compressing',
        'mekanism:factory/elite/combining',
        'mekanism:factory/elite/purifying',
        'mekanism:factory/elite/injecting',
        'mekanism:factory/elite/infusing',
        'mekanism:factory/elite/infusing',
        'mekanism:factory/elite/sawing',
        /*'mekanism:processing/iron/enriched',*/
        'mekanism:factory/ultimate/smelting',
        'mekanism:factory/ultimate/enriching',
        'mekanism:factory/ultimate/crushing',
        'mekanism:factory/ultimate/compressing',
        'mekanism:factory/ultimate/combining',
        'mekanism:factory/ultimate/purifying',
        'mekanism:factory/ultimate/injecting',
        'mekanism:factory/ultimate/infusing',
        'mekanism:factory/ultimate/infusing',
        'mekanism:factory/ultimate/sawing',
        /*'mekanism:processing/steel/enriched_iron_to_dust',*/
        'mekanism:factory/advanced/smelting',
        'mekanism:factory/advanced/enriching',
        'mekanism:factory/advanced/crushing',
        'mekanism:factory/advanced/compressing',
        'mekanism:factory/advanced/combining',
        'mekanism:factory/advanced/purifying',
        'mekanism:factory/advanced/injecting',
        'mekanism:factory/advanced/infusing',
        'mekanism:factory/advanced/infusing',
        'mekanism:factory/advanced/sawing',
        'enderio:void_chassis',
        'mekanismgenerators:fission_reactor_casing',
        'alltheores:iridium_ingot_from_ore',
        'alltheores:iridium_ingot_from_dust',
        'alltheores:iridium_ingot_from_raw',
        'alltheores:iridium_ingot_from_ore_blasting',
        'alltheores:iridium_ingot_from_dust_blasting',
        'alltheores:mek_processing/iridium/ingot/from_dust_blasting',
        'alltheores:iridium_ingot_from_raw_blasting',
        /*'jaopca:thermal_expansion.material_to_dust.iridium',
        'jaopca:thermal_expansion.raw_material_to_dust.iridium',
        'jaopca:mekanism.raw_storage_block_to_dust.iridium',
        'alltheores:mek_processing/iridium/dust/from_raw_ore',
        'alltheores:mek_processing/iridium/dust/from_ore',
        'alltheores:mek_processing/iridium/dust/from_raw_block',
        'jaopca:mekanism.raw_material_to_dust.iridium',
        'jaopca:mekanism.ore_to_dust.iridium',
        'alltheores:mek_processing/iridium/dust/from_dirty_dust',
        'alltheores:mek_processing/iridium/dust/from_ingot',
        'jaopca:mekanism.material_to_dust.iridium',
        'jaopca:thermal_expansion.ore_to_dust.iridium'*/
        'mekanismgenerators:reactor/glass',
        'mekanismgenerators:fission_reactor/control_rod_assembly',
        'mekanismgenerators:fission_reactor/casing',
        'mekanismgenerators:fission_reactor/fuel_assembly',
        'enderio:energy_conduit',
        'gtceu:arc_furnace/arc_uranium_dust',
        'biggerreactors:crafting/reactor/reactor_casing',
        'functionalstorage:oak_drawer_alternate_x1',
        'functionalstorage:oak_drawer_alternate_x2',
        'functionalstorage:oak_drawer_alternate_x4',
        'ae2:network/cables/glass_fluix',
        'ae2:network/parts/quartz_fiber_part',
        'avaritia:diamond_lattice',
        'avaritia:crystal_matrix_ingot',
        'biggerreactors:crafting/turbine/turbine_casing',
        'avaritia:infinity_catalyst',
        'allthemodium:unobtainium_gear',
        'allthemodium:vibranium_gear',
        'allthemodium:allthemodium_gear',
        'avaritia:infinity_ingot',
        'avaritia:neutron_compressor',
        'avaritia:neutron_collector',
        'avaritia:ultimate_stew',
        'avaritia:cosmic_meatballs',
        'avaritia:endest_pearl',
        'avaritia:skull_fire_sword',
        'avaritia:record_fragment',
        'mekanismgenerators:reactor/frame',
        'morered:red_alloy_ingot_from_jumbo_smelting',
        'allthemodium:vibranium_ingot_from_raw_smelting',
        'allthemodium:vibranium_ingot_from_dust_smelting',
        'allthemodium:allthemodium_ingot_from_raw_smelting',
        'allthemodium:allthemodium_ingot_from_dust_smelting',
        'allthemodium:unobtainium_ingot_from_raw_blasting',
        'allthemodium:unobtainium_ingot_from_dust_blasting',
        'allthemodium:allthemodium_ingot_from_raw_blasting',
        'allthemodium:allthemodium_ingot_from_dust_blasting',
        'allthemodium:vibranium_ingot_from_raw_blasting',
        'allthemodium:vibranium_ingot_from_dust_blasting',
        'allthemodium:unobtainium_ingot_from_raw_smelting',
        'allthemodium:unobtainium_ingot_from_dust_smelting',
        'seadwellers:lava_bucket_from_brimwood'

        



    ]
    for (let i of remove_id) {
        event.remove({id: i})
    }
})

ServerEvents.recipes(event => {
    let remove_input = [
        '#alltheores:ore_hammers'
    ]
    for (let i of remove_input) {
        event.remove({input: i})
    }
})
//移除熔炉、高炉、TE感应炉的输出配方
ServerEvents.recipes(event => {
    let remove_output = [
        'mekanism:ingot_uranium',
        'biggerreactors:uranium_ingot',
        'alltheores:uranium_ingot',
        'alltheores:uranium_ingot',
        'allthemodium:allthemodium_ingot',
        'allthemodium:vibranium_ingot',
        'allthemodium:unobtainium_ingot'
    ]
    for (let i of remove_output) {
        event.remove({output: i, type: 'minecraft:smelting'})
        event.remove({output: i, type: 'minecraft:blasting'})
        event.remove({output: i, type: 'thermal:smelter'})
    }
})