ServerEvents.recipes(event => {
    //MEK机壳合成1
    event.recipes.gtceu.assembler('hbx:gt_mek_casing_0')
        .itemInputs(['12x #forge:double_plates/black_steel', '8x gtceu:tempered_glass', '#forge:gears/osmium', 'gtceu:mv_sensor', '#forge:frames/steel', '32x #forge:circuits/basic'])
        .itemOutputs('mekanism:steel_casing')
        .EUt(126)
        .duration(140)
        .circuit(1)
    //MEK机壳合成2
    event.recipes.gtceu.assembler('hbx:gt_mek_casing_1')
        .itemInputs(['2x otto:alloy_reinforced_double_plate', '8x gtceu:tempered_glass', 'otto:alloy_atomic_double_plate', 'gtceu:mv_sensor', '#forge:frames/steel', '2x mekanism:elite_control_circuit'])
        .itemOutputs('3x mekanism:steel_casing')
        .EUt(126)
        .duration(200)
        .circuit(3)
    //BR裂变机壳
    event.recipes.gtceu.assembler('hbx:gt_br_reactor_casing')
        .itemInputs(['2x enderio:double_layer_capacitor', '8x #forge:ingots/energetic_alloy', '8x #forge:double_plates/steel', '4x enderio:void_chassis', '4x enderio:dark_bimetal_gear'])
        .inputFluids(Fluid.of('gtceu:tin', 1000))
        .itemOutputs('12x biggerreactors:reactor_casing')
        .EUt(32)
        .duration(1800)
        .circuit(5)
    //BR涡轮机壳
    event.recipes.gtceu.assembler('hbx:gt_br_turbine_casing')
        .itemInputs(['16x #forge:ingots/enderium', '16x #forge:plates/stainless_steel', '16x #forge:ingots/cyanite', "64x #ae2:all_quartz", '64x biggerreactors:graphite_ingot'])
        .itemOutputs('32x biggerreactors:turbine_casing')
        .inputFluids(Fluid.of('gtceu:tin', 1000))
        .EUt(480)
        .duration(1200)
        .circuit(5)
    event.recipes.gtceu.assembler('hbx:gt_eio_ender_steel_casing')
        .itemInputs(['2x enderio:octadic_capacitor', '2x #forge:ingots/end_steel', '#forge:ingots/dark_steel'])
        .itemOutputs('otto:ender_steel_casing')
        .EUt(16)
        .duration(2)
    event.recipes.gtceu.assembler('hbx:gt_eio_melodic_casing')
        .itemInputs(['otto:ender_steel_casing', '2x enderio:octadic_capacitor', '2x #forge:ingots/end_steel', '#forge:ingots/dark_steel'])
        .itemOutputs('otto:melodic_casing')
        .EUt(16)
        .duration(2)
})