ServerEvents.recipes(event => {
    event.recipes.gtceu.chemical_reactor('hbx:mek_o2_to_gt_o2')
        .inputFluids(Fluid.of("mekanism:oxygen", 1000))
        .outputFluids(Fluid.of("gtceu:oxygen"), 1000)
        .EUt(8)
        .duration(1)
        .circuit(32)
    event.recipes.gtceu.chemical_reactor('hbx:mek_h2_to_gt_h2')
        .inputFluids(Fluid.of("mekanism:flowing_hydrogen", 1000))
        .outputFluids(Fluid.of("gtceu:hydrogen"), 1000)
        .EUt(8)
        .duration(1)
        .circuit(32)
    event.recipes.gtceu.chemical_reactor('hbx:mek_h2so4_to_gt_h2so4')
        .inputFluids(Fluid.of("mekanism:sulfuric_acid", 1000))
        .outputFluids(Fluid.of("gtceu:sulfuric_acid"), 1000)
        .EUt(8)
        .duration(1)
        .circuit(32)
    
})