ServerEvents.recipes(event => {
    event.recipes.gtceu.forming_press('hbx:matrix_ingot')
        .itemInputs(['4x avaritia:diamond_lattice', '4x #forge:ingots/netherite', '2x #forge:gems/nether_star'])
        .itemOutputs('avaritia:crystal_matrix_ingot')
        .notConsumable('gtceu:ingot_casting_mold')
        .EUt(32768)
        .duration(2400)
    event.recipes.gtceu.forming_press('hbx:matrix_ingot_9x')
        .itemInputs(['36x avaritia:diamond_lattice', '36x #forge:ingots/netherite', '18x #forge:gems/nether_star'])
        .itemOutputs('avaritia:crystal_matrix')
        .notConsumable('gtceu:block_casting_mold')
        .EUt(32768)
        .duration(2400)
})