JEIEvents.hideItems(event => {
    event.hide(/botanypots:(white|orange|magenta|light_blue|yellow|lime|pink|gray|light_gray|cyan|purple|blue|brown|green|red|black)_.+/)
    Color.DYE.forEach(color => {
        ['clear_glass', 'fused_quartz'].forEach(glass => {
                event.hide(`enderio:${glass}_${color}`)
                event.hide(`enderio:${glass}_p_${color}`)
                event.hide(`enderio:${glass}_np_${color}`)
                event.hide(`enderio:${glass}_m_${color}`)
                event.hide(`enderio:${glass}_nm_${color}`)
                event.hide(`enderio:${glass}_a_${color}`)
                event.hide(`enderio:${glass}_na_${color}`)
                event.hide(`enderio:${glass}_d_${color}`)
                event.hide(`enderio:${glass}_dp_${color}`)
                event.hide(`enderio:${glass}_dnp_${color}`)
                event.hide(`enderio:${glass}_dm_${color}`)
                event.hide(`enderio:${glass}_dnm_${color}`)
                event.hide(`enderio:${glass}_da_${color}`)
                event.hide(`enderio:${glass}_dna_${color}`)
                event.hide(`enderio:${glass}_e_${color}`)
                event.hide(`enderio:${glass}_ep_${color}`)
                event.hide(`enderio:${glass}_enp_${color}`)
                event.hide(`enderio:${glass}_em_${color}`)
                event.hide(`enderio:${glass}_enm_${color}`)
                event.hide(`enderio:${glass}_ea_${color}`)
                event.hide(`enderio:${glass}_ena_${color}`)
                event.hide(`botanypotstiers:elite_${color}_terracotta_botany_pot`)
                event.hide(`botanypotstiers:elite_${color}_terracotta_hopper_botany_pot`)
                event.hide(`botanypotstiers:elite_${color}_concrete_botany_pot`)
                event.hide(`botanypotstiers:elite_${color}_concrete_hopper_botany_pot`)
                event.hide(`botanypotstiers:elite_${color}_glazed_terracotta_botany_pot`)
                event.hide(`botanypotstiers:elite_${color}_glazed_terracotta_hopper_botany_pot`)
                event.hide(`botanypotstiers:ultra_${color}_terracotta_botany_pot`)
                event.hide(`botanypotstiers:ultra_${color}_terracotta_hopper_botany_pot`)
                event.hide(`botanypotstiers:ultra_${color}_concrete_botany_pot`)
                event.hide(`botanypotstiers:ultra_${color}_concrete_hopper_botany_pot`)
                event.hide(`botanypotstiers:ultra_${color}_glazed_terracotta_botany_pot`)
                event.hide(`botanypotstiers:ultra_${color}_glazed_terracotta_hopper_botany_pot`)
                event.hide(`botanypotstiers:creative_${color}_terracotta_botany_pot`)
                event.hide(`botanypotstiers:creative_${color}_terracotta_hopper_botany_pot`)
                event.hide(`botanypotstiers:creative_${color}_concrete_botany_pot`)
                event.hide(`botanypotstiers:creative_${color}_concrete_hopper_botany_pot`)
                event.hide(`botanypotstiers:creative_${color}_glazed_terracotta_botany_pot`)
                event.hide(`botanypotstiers:creative_${color}_glazed_terracotta_hopper_botany_pot`)
        })       
    });
})  

